### ISSUE TITLE
The game Won't start

### ISSUE THREAD

**Issue by DWGem** [Y0ungSandwich/Mech-and-Magic#163]
The game won't let me play.
I have reinstalled several times but nothing seems to be working.
Please help.
[31/5/2017 12:11:54 PM] Console Cleared
[31/5/2017 12:12:02 PM] Logging into Minecraft!
[31/5/2017 12:12:07 PM] Launching pack Mech & Magic 1.1.9 for Minecraft 1.10.2
[31/5/2017 12:12:07 PM] Launching Minecraft with the following arguments (user related stuff has been removed): [C:\Program Files\Java\jre7\bin\javaw, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -XX:-OmitStackTraceInFastThrow, -Xms256M, -Xmx4096M, -XX:PermSize=256M, -Duser.language=en, -Duser.country=US, -Dfml.log.level=INFO, -XX:+UseConcMarkSweepGC, -XX:+CMSIncrementalMode, -XX:-UseAdaptiveSizePolicy, -Djava.library.path=USERSDIR\Instances\MechMagic\bin\natives, -cp, USERSDIR\ATLauncher.exe;anything;USERSDIR\Instances\MechMagic\jarmods\forge-1.10.2-12.18.3.2254-universal.jar;USERSDIR\Instances\MechMagic\bin\launchwrapper-1.12.jar;USERSDIR\Instances\MechMagic\bin\asm-all-5.0.3.jar;USERSDIR\Instances\MechMagic\bin\jline-2.13.jar;USERSDIR\Instances\MechMagic\bin\akka-actor_2.11-2.3.3.jar;USERSDIR\Instances\MechMagic\bin\config-1.2.1.jar;USERSDIR\Instances\MechMagic\bin\scala-actors-migration_2.11-1.1.0.jar;USERSDIR\Instances\MechMagic\bin\scala-compiler-2.11.1.jar;USERSDIR\Instances\MechMagic\bin\scala-continuations-library_2.11-1.0.2.jar;USERSDIR\Instances\MechMagic\bin\scala-continuations-plugin_2.11.1-1.0.2.jar;USERSDIR\Instances\MechMagic\bin\scala-library-2.11.1.jar;USERSDIR\Instances\MechMagic\bin\scala-parser-combinators_2.11-1.0.1.jar;USERSDIR\Instances\MechMagic\bin\scala-reflect-2.11.1.jar;USERSDIR\Instances\MechMagic\bin\scala-swing_2.11-1.0.1.jar;USERSDIR\Instances\MechMagic\bin\scala-xml_2.11-1.0.2.jar;USERSDIR\Instances\MechMagic\bin\lzma-0.0.1.jar;USERSDIR\Instances\MechMagic\bin\jopt-simple-4.6.jar;USERSDIR\Instances\MechMagic\bin\vecmath-1.5.2.jar;USERSDIR\Instances\MechMagic\bin\trove4j-3.0.3.jar;USERSDIR\Instances\MechMagic\bin\netty-1.6.jar;USERSDIR\Instances\MechMagic\bin\oshi-core-1.1.jar;USERSDIR\Instances\MechMagic\bin\jna-3.4.0.jar;USERSDIR\Instances\MechMagic\bin\platform-3.4.0.jar;USERSDIR\Instances\MechMagic\bin\icu4j-core-mojang-51.2.jar;USERSDIR\Instances\MechMagic\bin\codecjorbis-20101023.jar;USERSDIR\Instances\MechMagic\bin\codecwav-20101023.jar;USERSDIR\Instances\MechMagic\bin\libraryjavasound-20101123.jar;USERSDIR\Instances\MechMagic\bin\librarylwjglopenal-20100824.jar;USERSDIR\Instances\MechMagic\bin\soundsystem-20120107.jar;USERSDIR\Instances\MechMagic\bin\netty-all-4.0.23.Final.jar;USERSDIR\Instances\MechMagic\bin\guava-17.0.jar;USERSDIR\Instances\MechMagic\bin\commons-lang3-3.3.2.jar;USERSDIR\Instances\MechMagic\bin\commons-io-2.4.jar;USERSDIR\Instances\MechMagic\bin\commons-codec-1.9.jar;USERSDIR\Instances\MechMagic\bin\jinput-2.0.5.jar;USERSDIR\Instances\MechMagic\bin\jutils-1.0.0.jar;USERSDIR\Instances\MechMagic\bin\gson-2.2.4.jar;USERSDIR\Instances\MechMagic\bin\authlib-1.5.22.jar;USERSDIR\Instances\MechMagic\bin\realms-1.9.8.jar;USERSDIR\Instances\MechMagic\bin\commons-compress-1.8.1.jar;USERSDIR\Instances\MechMagic\bin\httpclient-4.3.3.jar;USERSDIR\Instances\MechMagic\bin\commons-logging-1.1.3.jar;USERSDIR\Instances\MechMagic\bin\httpcore-4.3.2.jar;USERSDIR\Instances\MechMagic\bin\fastutil-7.0.12_mojang.jar;USERSDIR\Instances\MechMagic\bin\log4j-api-2.0-beta9.jar;USERSDIR\Instances\MechMagic\bin\log4j-core-2.0-beta9.jar;USERSDIR\Instances\MechMagic\bin\lwjgl-2.9.4-nightly-20150209.jar;USERSDIR\Instances\MechMagic\bin\lwjgl_util-2.9.4-nightly-20150209.jar;USERSDIR\Instances\MechMagic\bin\minecraft.jar, net.minecraft.launchwrapper.Launch, --username, REDACTED, --version, 1.10.2, --gameDir, USERSDIR\Instances\MechMagic, --assetsDir, USERSDIR\Configs\Resources, --assetIndex, 1.10, --uuid, 19fe3d889974476ea6e55dea4848aa70, --accessToken, REDACTED, --userType, mojang, --versionType, release, --width=854, --height=480, --tweakClass=net.minecraftforge.fml.common.launcher.FMLTweaker, --versionType, Forge]
[31/5/2017 12:12:08 PM] 2017-05-31 12:12:08,376 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[31/5/2017 12:12:08 PM] 2017-05-31 12:12:08,378 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[31/5/2017 12:12:08 PM] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[31/5/2017 12:12:08 PM] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[31/5/2017 12:12:08 PM] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[31/5/2017 12:12:08 PM] [main/INFO] [FML]: Forge Mod Loader version 12.18.3.2254 for Minecraft 1.10.2 loading
[31/5/2017 12:12:08 PM] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.7.0_79, running on Windows 8.1:amd64:6.3, installed at C:\Program Files\Java\jre7
[31/5/2017 12:12:08 PM] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: java.lang.UnsupportedClassVersionError: appeng/coremod/AppEngCore : Unsupported major.minor version 52.0
[31/5/2017 12:12:08 PM] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[31/5/2017 12:12:08 PM] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.lang.ClassLoader.defineClass(Unknown Source)
[31/5/2017 12:12:08 PM] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.security.SecureClassLoader.defineClass(Unknown Source)
[31/5/2017 12:12:08 PM] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.net.URLClassLoader.defineClass(Unknown Source)
[31/5/2017 12:12:08 PM] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.net.URLClassLoader.access$100(Unknown Source)
[31/5/2017 12:12:08 PM] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[31/5/2017 12:12:08 PM] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[31/5/2017 12:12:08 PM] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.security.AccessController.doPrivileged(Native Method)
[31/5/2017 12:12:08 PM] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[31/5/2017 12:12:08 PM] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[31/5/2017 12:12:08 PM] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[31/5/2017 12:12:08 PM] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[31/5/2017 12:12:08 PM] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.lang.Class.forName0(Native Method)
[31/5/2017 12:12:08 PM] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.lang.Class.forName(Unknown Source)
[31/5/2017 12:12:08 PM] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:564)
[31/5/2017 12:12:08 PM] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:425)
[31/5/2017 12:12:08 PM] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:255)
[31/5/2017 12:12:08 PM] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:102)
[31/5/2017 12:12:08 PM] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:79)
[31/5/2017 12:12:08 PM] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:41)
[31/5/2017 12:12:08 PM] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:138)
[31/5/2017 12:12:08 PM] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[31/5/2017 12:12:08 PM] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[31/5/2017 12:12:08 PM] [main/ERROR] [FML]: An error occurred trying to configure the minecraft home at **USERSDIR**\Instances\MechMagic for Forge Mod Loader
[31/5/2017 12:12:08 PM] java.lang.UnsupportedClassVersionError: appeng/coremod/AppEngCore : Unsupported major.minor version 52.0
[31/5/2017 12:12:08 PM] 	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_79]
[31/5/2017 12:12:08 PM] 	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.7.0_79]
[31/5/2017 12:12:08 PM] 	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.7.0_79]
[31/5/2017 12:12:08 PM] 	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.7.0_79]
[31/5/2017 12:12:08 PM] 	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.7.0_79]
[31/5/2017 12:12:08 PM] 	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_79]
[31/5/2017 12:12:08 PM] 	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_79]
[31/5/2017 12:12:08 PM] 	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_79]
[31/5/2017 12:12:08 PM] 	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0_79]
[31/5/2017 12:12:08 PM] 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
[31/5/2017 12:12:08 PM] 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_79]
[31/5/2017 12:12:08 PM] 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_79]
[31/5/2017 12:12:08 PM] 	at java.lang.Class.forName0(Native Method) ~[?:1.7.0_79]
[31/5/2017 12:12:08 PM] 	at java.lang.Class.forName(Unknown Source) ~[?:1.7.0_79]
[31/5/2017 12:12:08 PM] 	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:564) ~[forge-1.10.2-12.18.3.2254-universal.jar:?]
[31/5/2017 12:12:08 PM] 	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:425) ~[forge-1.10.2-12.18.3.2254-universal.jar:?]
[31/5/2017 12:12:08 PM] 	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:255) ~[forge-1.10.2-12.18.3.2254-universal.jar:?]
[31/5/2017 12:12:08 PM] 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:102) [forge-1.10.2-12.18.3.2254-universal.jar:?]
[31/5/2017 12:12:08 PM] 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:79) [forge-1.10.2-12.18.3.2254-universal.jar:?]
[31/5/2017 12:12:08 PM] 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:41) [forge-1.10.2-12.18.3.2254-universal.jar:?]
[31/5/2017 12:12:08 PM] 	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:138) [forge-1.10.2-12.18.3.2254-universal.jar:?]
[31/5/2017 12:12:08 PM] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
[31/5/2017 12:12:08 PM] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[31/5/2017 12:12:08 PM] Exception in thread "main" [12:12:08] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.UnsupportedClassVersionError: appeng/coremod/AppEngCore : Unsupported major.minor version 52.0
[31/5/2017 12:12:08 PM] [12:12:08] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[31/5/2017 12:12:08 PM] [12:12:08] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.defineClass(Unknown Source)
[31/5/2017 12:12:08 PM] [12:12:08] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.security.SecureClassLoader.defineClass(Unknown Source)
[31/5/2017 12:12:08 PM] [12:12:08] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader.defineClass(Unknown Source)
[31/5/2017 12:12:08 PM] [12:12:08] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader.access$100(Unknown Source)
[31/5/2017 12:12:08 PM] [12:12:08] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[31/5/2017 12:12:08 PM] [12:12:08] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[31/5/2017 12:12:08 PM] [12:12:08] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.security.AccessController.doPrivileged(Native Method)
[31/5/2017 12:12:08 PM] [12:12:08] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[31/5/2017 12:12:08 PM] [12:12:08] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[31/5/2017 12:12:08 PM] [12:12:08] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[31/5/2017 12:12:08 PM] [12:12:08] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[31/5/2017 12:12:08 PM] [12:12:08] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Class.forName0(Native Method)
[31/5/2017 12:12:08 PM] [12:12:08] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Class.forName(Unknown Source)
[31/5/2017 12:12:08 PM] [12:12:08] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:564)
[31/5/2017 12:12:08 PM] [12:12:08] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:425)
[31/5/2017 12:12:08 PM] [12:12:08] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:255)
[31/5/2017 12:12:08 PM] [12:12:08] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:102)
[31/5/2017 12:12:08 PM] [12:12:08] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:79)
[31/5/2017 12:12:08 PM] [12:12:08] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:41)
[31/5/2017 12:12:08 PM] [12:12:08] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:138)
[31/5/2017 12:12:08 PM] [12:12:08] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[31/5/2017 12:12:08 PM] [12:12:08] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[31/5/2017 12:12:08 PM] Checking for updated files!
[31/5/2017 12:12:09 PM] Updates found!
[31/5/2017 12:12:09 PM] Checking for updated files!
[31/5/2017 12:12:09 PM] Updates found!
[31/5/2017 12:12:09 PM] Downloading Launcher File packs.json
[31/5/2017 12:12:09 PM] File **USERSDIR**\Configs\JSON\packs.json couldn't be deleted
[31/5/2017 12:12:09 PM] File **USERSDIR**\Configs\JSON\packs.json couldn't be deleted
[31/5/2017 12:12:09 PM] File **USERSDIR**\Configs\JSON\packs.json couldn't be deleted
[31/5/2017 12:12:12 PM] Finished downloading updated files!
[31/5/2017 12:12:12 PM] Loading Language: English

this is the message it has every time I try to play

**Comment by Y0ungSandwich** [comment]
Install Java 8
